image: egon0/docker-with-buildx-and-git:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    D_IMAGE_TAG: egon0/minio-multiarch
    D_LATEST_TAG: egon0/minio-multiarch:latest
  script:
    - echo $IMAGE_TAG:$(date +%Y-%m-%d)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker buildx create --use --name A$CI_COMMIT_SHORT_SHA
    - docker buildx build --platform $BUILD_PLATFORMS --push -t $IMAGE_TAG:$(date +%Y-%m-%d) -t $CI_REGISTRY_IMAGE:latest -t $D_IMAGE_TAG:$(date +%Y-%m-%d) -t $D_LATEST_TAG .
